"""New baseline: Cascade Mask R-CNN with AdamW + cosine schedule.

Use this with the 85/15 split generated by:

    python tools/convert_hw3_to_coco.py --val-ratio 0.15
"""

_base_ = "./cascade_mask_rcnn_r50_fpn_hw3.py"

train_cfg = dict(type="EpochBasedTrainLoop", max_epochs=36, val_interval=1)

optim_wrapper = dict(
    _delete_=True,
    type="AmpOptimWrapper",
    optimizer=dict(
        type="AdamW",
        lr=1e-4,
        betas=(0.9, 0.999),
        weight_decay=1e-4,
    ),
    clip_grad=dict(max_norm=5.0, norm_type=2),
)

param_scheduler = [
    dict(
        type="LinearLR",
        start_factor=0.1,
        by_epoch=False,
        begin=0,
        end=500,
    ),
    dict(
        type="CosineAnnealingLR",
        eta_min=1e-6,
        begin=0,
        end=36,
        by_epoch=True,
        convert_to_iter_based=True,
    ),
]

log_processor = dict(type="LogProcessor", window_size=20, by_epoch=True)
